Add encoding and error handling to log file reading
Fixes 'utf-8' codec can't decode byte 0x8b in position 1: invalid start
byte.

```
Traceback (most recent call last):
  File "/root/regress-stack/.venv/bin/regress-stack", line 10, in <module>
    sys.exit(main())
             ^^^^^^
  File "/root/regress-stack/.venv/lib/python3.12/site-packages/click/core.py", line 1442, in __call__
    return self.main(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/regress-stack/.venv/lib/python3.12/site-packages/click/core.py", line 1363, in main
    rv = self.invoke(ctx)
         ^^^^^^^^^^^^^^^^
  File "/root/regress-stack/.venv/lib/python3.12/site-packages/click/core.py", line 1830, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/regress-stack/.venv/lib/python3.12/site-packages/click/core.py", line 1226, in invoke
    return ctx.invoke(self.callback, **ctx.params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/regress-stack/.venv/lib/python3.12/site-packages/click/core.py", line 794, in invoke
    return callback(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/regress-stack/src/regress_stack/core/utils.py", line 53, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/root/regress-stack/src/regress_stack/cli/test.py", line 136, in test
    collect_logs()
  File "/root/regress-stack/src/regress_stack/cli/utils.py", line 31, in collect_logs
    _output_log_file(log_file)
  File "/root/regress-stack/src/regress_stack/cli/utils.py", line 14, in _output_log_file
    for line in log_file:
  File "<frozen codecs>", line 322, in decode
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x8b in position 1: invalid start byte
```

Signed-off-by: Felipe Reyes <felipe.reyes@canonical.com>